### PR TITLE
EOS-14283: NFS ADDB: Trace points for all motr operations

### PR DESCRIPTION
**Pull request by vimalraghwani20**
**Problem Statement**
EOS-14283: NFS ADDB: Trace points for all motr operations

**Problem Description**
There was no way NFS ADDB can trace the time required for motr apis. We need to come up with connection point where we can trace the motr api.

**Solution Overview**
Added performance counter START and END before and after Motr api.
Also, Added traces for sm_id and sm_state after motr api completed to trace the motr api in there addb call graph.

**Unit Test Cases**
image

### CODE REVIEW

**Review by AtitaShirwaikar — APPROVED** [review]
+1, just fix the alignment

**Review by pratyush-seagate — APPROVED** [review]
LGTM, +1

**Review by Anilsindhi — APPROVED** [review]
LGTM, +1

**Review by sachinpunadikar — APPROVED** [review]
+1

**Pull request merged**
